version: "2.2"
pipelines:
  - id: postgres-to-kafka
    status: running
    description: Postgres to Kafka (CDC)
    connectors:
      - id: postgres-source
        type: source
        plugin: builtin:postgres
        settings:
          tables: "public.employees"
          url: "postgresql://meroxauser:meroxapass@custom-pg-0:5432/meroxadb"
          cdcMode: "logrepl"
          logrepl.slotName: "conduit_slot"
          logrepl.publicationName: "conduit_pub"
          logrepl.autoCleanup: "true"
          logrepl.withAvroSchema: "false"
          snapshotMode: "never"
          sdk.batch.size: 10000
          sdk.batch.delay: "1s"
          sdk.schema.extract.key.enabled: false
          sdk.schema.extract.payload.enabled: false
      - id: kafka-destination
        type: destination
        plugin: builtin:kafka
        name: kafka-destination
        settings:
          servers: "custom-kafka-0:9092"
          topic: "public.employees"
          compression: "none"
          sdk.schema.extract.key.enabled: false
          sdk.schema.extract.payload.enabled: false
